### ISSUE TITLE
Verbose Error: Regex invalid group reference pointer 

### ISSUE THREAD

**Issue by unl1k3ly** [1N3/Sn1per#264]
Hi, awesome tool !

I ran it for the very 1st time and got the follow along the execution. It did completed just fine though.

Cheers

```
====================================================================================•x[2020-04-30](13:50)x•
 GATHERING WEB FINGERPRINT 
====================================================================================•x[2020-04-30](13:50)x•
Traceback (most recent call last):
  File "/usr/local/bin/webtech", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/webtech/__main__.py", line 54, in main
    wt.start()
  File "/usr/local/lib/python3.7/dist-packages/webtech/webtech.py", line 132, in start
    temp_output = self.start_from_url(url)
  File "/usr/local/lib/python3.7/dist-packages/webtech/webtech.py", line 172, in start_from_url
    return self.perform(target)
  File "/usr/local/lib/python3.7/dist-packages/webtech/webtech.py", line 222, in perform
    target.check_html(tech, html)
  File "/usr/local/lib/python3.7/dist-packages/webtech/target.py", line 221, in check_html
    matches = re.search(source, self.data['html'], re.IGNORECASE)
  File "/usr/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 501, in _parse
    code = _escape(source, this, state)
  File "/usr/lib/python3.7/sre_parse.py", line 399, in _escape
    raise source.error("invalid group reference %d" % group, len(escape) - 1)
re.error: invalid group reference 1 at position 130
```

**Comment by unl1k3ly** [comment]
Thank you, since I was running in a dock, we might need to commit changes to the image. Thanks once again @1N3
