### ISSUE TITLE
Checking for WAF error

### ISSUE THREAD

**Issue by litt1eb0yy** [1N3/Sn1per#375]
```
 CHECKING FOR WAF 
====================================================================================•x[2021-11-10](10:14)x•
Traceback (most recent call last):
  File "/usr/local/bin/wafw00f", line 4, in <module>
    __import__('pkg_resources').run_script('wafw00f==2.1.0', 'wafw00f')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1436, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/wafw00f' not found in metadata at '/usr/lib/python3/dist-packages/wafw00f-2.1.0.egg-info'
```

**Comment by 1N3** [comment]
Haven't seen this one yet, but since I don't manage the Wafw00f project, there's not much I can do about that here. You will need to open an issue with the project owner if you think it's a bug.
