### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lnkakalink** [1N3/Sn1per#94]
Hi i start sniper and have error 

Smartmatch is experimental at /usr/bin/dnsenum line 698.
Smartmatch is experimental at /usr/bin/dnsenum line 698.

/usr/bin/sniper: line 1135: [: ==: unary operator expected

/usr/bin/sniper: line 998: [: ==: unary operator expected
/usr/bin/goohak: line 13: //: Is a directory

Traceback (most recent call last):
  File "/usr/bin/wafw00f", line 8, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/wafw00f/__init__.py", line 808, in main
    if attacker.normalrequest() is None:
  File "/usr/lib/python2.7/dist-packages/wafw00f/__init__.py", line 96, in normalrequest
    return self.request(usecache=usecache, cacheresponse=cacheresponse, headers=headers)
  File "/usr/lib/python2.7/dist-packages/wafw00f/lib/evillib.py", line 323, in request
    h.request(method, path, headers=headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 848, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 282, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))

**Comment by 1N3** [comment]
Hey, thanks for the heads up... looks like there was a error in the Blackarch checks that were added so I've went ahead and fixed those. Can you check the latest public release and let me know if that works for you?

**Comment by lnkakalink** [comment]
Hi i re-install 

root@kali:~/Sn1per# ./install.sh
                ____               
    _________  /  _/___  ___  _____
   / ___/ __ \ / // __ \/ _ \/ ___/
  (__  ) / / // // /_/ /  __/ /    
 /____/_/ /_/___/ .___/\___/_/     
               /_/                 

 + -- --=[http://crowdshield.com

 + -- --=[This script will install sniper under /usr/share/sniper. Are you sure you want to continue?
y
 + -- --=[Installing package dependencies...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'ruby' instead of 'rubygems'
Note, selecting 'xprobe' instead of 'xprobe2'
aha is already the newest version (0.4.10.6-3).
amap is already the newest version (5.4-4).
cisco-torch is already the newest version (0.4b-1kali4).
curl is already the newest version (7.55.0-1).
cutycapt is already the newest version (0.0~svn10-0.1).
dirb is already the newest version (2.22-0kali3).
dnsenum is already the newest version (1.2.4.2-0kali1).
dnsrecon is already the newest version (0.8.10-0kali1).
dos2unix is already the newest version (7.3.4-3).
enum4linux is already the newest version (0.8.9-1kali2).
host is already the newest version (1:9.10.3.dfsg.P4-12.5).
hydra is already the newest version (8.6-1).
iceweasel is already the newest version (52.3.0esr-2).
libxml2-utils is already the newest version (2.9.4+dfsg1-3.1).
metasploit-framework is already the newest version (4.16.2-0kali1).
nbtscan is already the newest version (1.5.1-6+b2).
nmap is already the newest version (7.60-1).
php is already the newest version (1:7.0+54).
php-curl is already the newest version (1:7.0+54).
python is already the newest version (2.7.13-2).
rpcbind is already the newest version (0.2.3-0.6).
ruby is already the newest version (1:2.3.3).
smtp-user-enum is already the newest version (1.2-1kali2).
sqlmap is already the newest version (1.1.8-1).
sslscan is already the newest version (1.11.10-rbsec-0kali1).
sslyze is already the newest version (0.12-0kali1).
theharvester is already the newest version (2.7-0kali1).
unicornscan is already the newest version (0.4.7-1kali2).
uniscan is already the newest version (6.3-0kali1).
waffit is already the newest version (0.9.3-0kali2).
whatweb is already the newest version (0.4.8~git20161009-1).
whois is already the newest version (5.2.18).
xprobe is already the newest version (0.3-3).
zenmap is already the newest version (7.60-1).
arachni is already the newest version (1.5.1-0kali1).
nikto is already the newest version (1:2.1.6+git20150709-0kali1).
wpscan is already the newest version (2.9.3-0kali1).
The following packages were automatically installed and are no longer required:
  jsql libass5 libavdevice57 libbluray1 libcoin80v5 libdap23 libebur128-1
  libevent-core-2.0-5 libevent-openssl-2.0-5 libevent-pthreads-2.0-5
  libgfortran3 libgraphicsmagick-q16-3 libhunspell-1.4-0 libiso9660-8
  libjs-mochikit liblua5.1-0 libmad0 libntfs-3g871 libopenscenegraph100v5
  libopenthreads20 libpango1.0-0 libpangox-1.0-0 libpcre16-3 libperl5.24
  libqgis-analysis2.14.17 libqgis-core2.14.11 libqgis-core2.14.17
  libqgis-gui2.14.11 libqgis-gui2.14.17 libqgis-networkanalysis2.14.11
  libqgis-networkanalysis2.14.17 libqgis-server2.14.17 libqgispython2.14.11
  libqgispython2.14.17 libqgsttools-p1 libqt5multimedia5-plugins
  libqt5multimediawidgets5 libradare2-1.1 libsdl2-2.0-0 liburcu4 libuv1
  libuv1-dev libvcdinfo0 libwebpmux2 libwireshark8 libwiretap6 libwsutil7
  libx265-116 libx265-95 libxine2 libxine2-bin libxine2-doc libxine2-ffmpeg
  libxine2-misc-plugins libxine2-plugins linux-image-4.9.0-kali3-amd64
  python-advancedhttpserver python-alembic python-boltons python-cheetah
  python-dap python-editor python-formencode python-geoip2 python-geojson
  python-icalendar python-maxminddb python-mpltoolkits.basemap python-openid
  python-pampy python-paste python-pastedeploy python-pastedeploy-tpl
  python-pastescript python-pluginbase python-pyotp python-scgi
  python-smoke-zephyr python-tempita python-tzlocal
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/__init__.py", line 52, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 59, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 32, in vendored
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 47, in <module>
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by lnkakalink** [comment]
Hi i start and have error 
Smartmatch is experimental at /usr/bin/dnsenum line 698.
Smartmatch is experimental at /usr/bin/dnsenum line 698.

**Comment by 1N3** [comment]
Hi, there were some bugs that were fixed in the latest version. To fix, you'll need to git clone sniper into a new directory and run ./install.sh to re-install. These errors should go away after.

**Comment by lnkakalink** [comment]
./install.sh 

 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/__init__.py", line 52, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 59, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 32, in vendored
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 47, in <module>
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by 1N3** [comment]
Just re-ran the latest install.sh script for Sn1per v4.0 on Kali 2.0 rolling and everything installed without error. If you're running any other Linux flavor, I'd recommend running the docker container for sniper instead as this will work on all platforms.
